# Generated by Django 3.2.7 on 2021-09-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Количество')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('factory', models.CharField(max_length=255, verbose_name='Завод')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('voidness', models.CharField(max_length=255, verbose_name='Пустотность')),
                ('surface', models.CharField(max_length=255, verbose_name='Поверхность')),
                ('colour', models.CharField(max_length=255, verbose_name='Цвет')),
                ('chamfer', models.BooleanField(default=True, verbose_name='Фаска')),
                ('endurance', models.CharField(max_length=255, verbose_name='Прочность')),
                ('frost_resistance', models.CharField(max_length=255, verbose_name='Морозостойкость')),
                ('water_absorption', models.CharField(max_length=255, verbose_name='Водопоглощение')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес 1 шт, кг')),
                ('packaging', models.CharField(max_length=255, verbose_name='Упаковка')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Склад')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Количество')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('resolution', models.CharField(max_length=255, verbose_name='Разрешение экрана')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Объем батареи')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('cd', models.BooleanField(default=True, verbose_name='Карта памяти')),
                ('cd_volume_max', models.CharField(max_length=255, verbose_name='Максимальный объем встраиваемой памяти')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Главная камера')),
                ('endurance', models.CharField(max_length=255, verbose_name='Прочность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
