# Generated by Django 3.2.7 on 2021-09-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210909_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Количество')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('factory', models.CharField(max_length=255, verbose_name='Завод')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('colour', models.CharField(max_length=255, verbose_name='Цвет')),
                ('density', models.CharField(max_length=255, verbose_name='Плотность')),
                ('endurance', models.CharField(max_length=255, verbose_name='Прочность')),
                ('thermal_conductivity', models.CharField(max_length=255, verbose_name='Теплопроводность')),
                ('frost_resistance', models.CharField(max_length=255, verbose_name='Морозостойкость')),
                ('weight', models.CharField(max_length=255, verbose_name='Вес 1 шт, кг')),
                ('packaging', models.CharField(max_length=255, verbose_name='Упаковка')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Склад')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BuildingBlocks',
        ),
    ]
