# Generated by Django 3.2.7 on 2021-09-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210909_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingBlock',
            new_name='BuildingBlocks',
        ),
    ]
