# Generated by Django 3.2.7 on 2021-09-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_buildingblock_buildingblocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brick',
            old_name='category',
            new_name='categor',
        ),
        migrations.RenameField(
            model_name='buildingblocks',
            old_name='category',
            new_name='categor',
        ),
    ]
