# Generated by Django 3.2.7 on 2021-09-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210910_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nam',
        ),
    ]
