# Generated by Django 3.2.7 on 2021-09-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_name_category_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nam',
            new_name='name',
        ),
    ]
