# Generated by Django 3.2.7 on 2021-09-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_nam_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='type',
            field=models.CharField(choices=[('facing', 'Облицовочный'), ('construction', 'Строительный'), ('warm_ceramics', 'Теплая керамика')], max_length=255, verbose_name='Тип'),
        ),
    ]
