# Generated by Django 3.2.7 on 2021-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_brick_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='brick',
            name='surface',
            field=models.CharField(choices=[('smooth', 'Гладкая'), ('grainy', 'Зернистая')], max_length=255, verbose_name='Поверхность'),
        ),
        migrations.AlterField(
            model_name='brick',
            name='voidness',
            field=models.CharField(choices=[('full-bodied', 'Полнотелый'), ('hollow', 'Пустотелый')], max_length=255, verbose_name='Пустотность'),
        ),
        migrations.AlterField(
            model_name='brick',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Вес 1 шт, кг'),
        ),
        migrations.AlterField(
            model_name='buildingblocks',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='buildingblocks',
            name='type',
            field=models.CharField(choices=[('aerated_concrete', 'Газобетонные'), ('ceramic', 'Керамические'), ('expanded_clay_concrete', 'Керамзитобетонные'), ('foundation_fbs', 'Фундаментные ФБС'), ('concrete', 'Бетонные'), ('pazogrebnevye', 'Пазогребневые')], max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='buildingblocks',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Вес 1 шт, кг'),
        ),
    ]
