# Generated by Django 3.2.7 on 2021-09-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210910_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingblocks',
            name='type',
            field=models.CharField(choices=[('aerated_concrete', 'Газобетонный'), ('ceramic', 'Керамический'), ('expanded_clay_concrete', 'Керамзитобетонный'), ('foundation_fbs', 'Фундаментные ФБС'), ('concrete', 'Бетонный'), ('pazogrebnevye', 'Пазогребневый')], max_length=255, verbose_name='Тип'),
        ),
    ]
