# Generated by Django 3.2.7 on 2021-09-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210919_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Количество')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('colour', models.CharField(max_length=255, verbose_name='Цвет')),
                ('sd', models.BooleanField(default=True, verbose_name='Наличие SD')),
                ('sd_volume_max', models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем встраиваемой памяти')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
